# Generated by Django 4.1.7 on 2023-07-10 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoodsDynamics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=11, verbose_name="价格"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="库存")),
                (
                    "color",
                    models.CharField(
                        default="", max_length=10, null=True, verbose_name="颜色"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        default="", max_length=40, null=True, verbose_name="尺寸/大小"
                    ),
                ),
                ("sales", models.IntegerField(verbose_name="销量")),
            ],
            options={
                "verbose_name": "商品动态表",
                "verbose_name_plural": "商品动态表",
                "db_table": "goods_dynamics_table",
            },
        ),
        migrations.CreateModel(
            name="GoodsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("name", models.CharField(max_length=20, verbose_name="类型名字")),
                ("image", models.ImageField(upload_to="goods_type", verbose_name="图片")),
            ],
            options={
                "verbose_name": "商品类型表",
                "verbose_name_plural": "商品类型表",
                "db_table": "goods_type",
            },
        ),
        migrations.CreateModel(
            name="RotationCharts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("name", models.CharField(max_length=10, verbose_name="名字")),
                (
                    "is_rotate",
                    models.BooleanField(
                        choices=[(0, "不轮播"), (1, "轮播")], default=1, verbose_name="是否轮播"
                    ),
                ),
                ("image", models.ImageField(upload_to="rotation", verbose_name="图片")),
            ],
            options={
                "verbose_name": "首页轮播图",
                "verbose_name_plural": "首页轮播图",
                "db_table": "rotation_image",
            },
        ),
        migrations.CreateModel(
            name="GoodsSPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("name", models.CharField(max_length=30, verbose_name="SUP名字")),
                ("detail", models.CharField(max_length=50, verbose_name="商品详情")),
                (
                    "goods_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodstype",
                        verbose_name="商品类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品SPU表",
                "verbose_name_plural": "商品SPU表",
                "db_table": "goods_spu",
            },
        ),
        migrations.CreateModel(
            name="GoodsSKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("name", models.CharField(max_length=50, verbose_name="商品名字")),
                (
                    "status",
                    models.BooleanField(
                        choices=[(0, "下架"), (1, "上架")], default=1, verbose_name="商品状态"
                    ),
                ),
                (
                    "goods_spu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodsspu",
                        verbose_name="商品SPU",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品SKU表",
                "verbose_name_plural": "商品SKU表",
                "db_table": "goods_sku",
            },
        ),
        migrations.CreateModel(
            name="GoodsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("image", models.ImageField(upload_to="goods")),
                (
                    "goods_dynamics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodsdynamics",
                        verbose_name="商品名字",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品图片表",
                "verbose_name_plural": "商品图片表",
                "db_table": "goods_image",
            },
        ),
        migrations.AddField(
            model_name="goodsdynamics",
            name="goods_sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.goodssku",
                verbose_name="商品SKU",
            ),
        ),
    ]
