# Generated by Django 4.1.7 on 2023-07-10 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodssku",
            name="goods_type",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.goodstype",
                verbose_name="商品类型",
            ),
        ),
    ]
