# Generated by Django 4.1.7 on 2023-07-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_goodssku_goods_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodstype",
            name="logo",
            field=models.CharField(default="", max_length=10, verbose_name="类型标志"),
        ),
    ]
