# Generated by Django 4.1.7 on 2023-07-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_goodstype_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodstype",
            name="logo",
            field=models.CharField(default="", max_length=20, verbose_name="类型标志"),
        ),
    ]
