# Generated by Django 4.1.7 on 2023-07-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "__first__"),
        ("goods", "0004_alter_goodstype_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("content", models.CharField(max_length=255, verbose_name="评论内容")),
                (
                    "score",
                    models.SmallIntegerField(
                        choices=[(1, "好评"), (2, "中评"), (3, "差评")],
                        default=1,
                        verbose_name="评分",
                    ),
                ),
                (
                    "goods_order",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.goodsorder",
                        verbose_name="商品订单",
                    ),
                ),
                (
                    "goods_sku",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodssku",
                        verbose_name="商品sku",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品评价表",
                "verbose_name_plural": "商品评价表",
                "db_table": "goods_comment",
            },
        ),
    ]
