# Generated by Django 4.1.7 on 2023-07-15 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goods", "0005_goodscomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodscomment",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
    ]
