# Generated by Django 4.1.7 on 2023-07-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_myuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(max_length=11, verbose_name="手机号"),
        ),
    ]
