# Generated by Django 4.1.7 on 2023-07-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="introduce",
            field=models.CharField(
                default="", max_length=100, null=True, verbose_name="个人介绍"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="phone",
            field=models.IntegerField(null=True, verbose_name="手机号"),
        ),
    ]
