# Generated by Django 4.1.7 on 2023-07-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_myuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="image",
            field=models.ImageField(
                default="user/default.jpg", upload_to="user", verbose_name="用户头像"
            ),
        ),
    ]
